### ISSUE TITLE
windows installshield2012 complains permission when starting the service

### ISSUE THREAD

**Issue by pcoder99** [snicoll-scratches/spring-boot-daemon#10]
I am using windows install shield 2012 configure the spring-boot-daemon-sample.exe as a windows  service. And pass "install" as the parameter to start up the service after installation. However, it reports error 1902, ask for sufficient privilege to start the service. 

Any hint for this kind of error ?

**Comment by snicoll** [comment]
Nope, sorry. We're using winsw so I'd rather ask over there.
