### ISSUE TITLE
Spring Profiles

### ISSUE THREAD

**Issue by bjordan2010** [snicoll-scratches/spring-boot-daemon#12]
Hi,

Is it possible to use Spring Profiles with this implementation?  For example, I want to run the service on a QA server with application-qa.properties and on a Production server with application.properites.

Thanks.

**Comment by snicoll** [comment]
`service.xml` has `startagument` where you can pass the profile that you want to enable for a given service. Please check the documentation of [winsw](https://github.com/kohsuke/winsw).
