### ISSUE TITLE
How is the Service User used?

### ISSUE THREAD

**Issue by isaacgainey-wsc** [snicoll-scratches/spring-boot-daemon#18]
Good Morning,

I have an inquiry about which user is calling java. The documentation leads me to believe that it's the service's "Log on as" account. However, I when start a Spring boot application as a service and its first console line is `example.SpringBootApplication : Starting SpringBoootApplication v0.0.1 on [local machine name] with PID 9052 (C:\SpringBootApp\springbootapp-0.0.1\lib\springbootapp-0.0.1.jar started by [local machine name] in C:\SpringBootApp\springbootapp-0.0.1)`. 
[local machine name] does contain a $ at the end of it.
This wouldn't be a concern, however, there are multiple database connections with usernames and passwords. And only as a service, the error log appears for each sqlserver `com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user '[local machine name]'. ClientConnectionId:[id]`, and other databases have invalid user and pass error messages.

My starting xml file was
```
 <serviceaccount>
    <domain>domain</domain>
     <user>user</user>
     <password>pass</password>
 </serviceaccount>
```
I've altered it to hard code to Down-Level Logon Name
```
 <serviceaccount>
     <user>domain\user</user>
     <password>pass</password>
 </serviceaccount>
```
and to User Principal Name
```
 <serviceaccount>
     <user>user@domain</user>
     <password>pass</password>
 </serviceaccount>
```
with the same results.

Here is the full current xml file.
```
<service>
	<id>@dist.project.id@</id>
	<name>@dist.project.name@</name>
	<description>@dist.project.description@</description>
	<workingdirectory>%BASE%\</workingdirectory>
	<logpath>%BASE%\logs</logpath>
	<logmode>reset</logmode>
	<startmode>manual</startmode>
	<priority>abovenormal</priority>

	<executable>java</executable>

	<startargument>-Dspring.application.admin.enabled=true</startargument>
	<startargument>-Dcom.sun.management.jmxremote.port=@dist.jmx.port@</startargument>
	<startargument>-Dcom.sun.management.jmxremote.authenticate=false</startargument>
	<startargument>-Dcom.sun.management.jmxremote.ssl=false</startargument>
	<startargument>-jar</startargument>
	<startargument>-Dloader.main=net.nicoll.boot.daemon.StartSpringBootService</startargument>
	<startargument>@dist.jar@</startargument>
	<startargument>@dist.start.class@</startargument>

	<stopexecutable>java</stopexecutable>
	<stopargument>-jar</stopargument>
	<stopargument>-Dloader.main=net.nicoll.boot.daemon.StopSpringBootService</stopargument>
	<stopargument>@dist.jar@</stopargument>
	<stopargument>@dist.jmx.port@</stopargument>

	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="restart" delay="30 sec"/>
	<onfailure action="none" />
	<resetfailure>1 hour</resetfailure>
    
 	<serviceaccount>
		<domain>domain</domain>
		<user>user</user>
		<password>pass</password>
	</serviceaccount>
</service>
```

**Comment by snicoll** [comment]
As [the readme states](https://github.com/snicoll-scratches/spring-boot-daemon/blob/master/README.adoc#windows), this project is simply a wrapper around [winsw](https://github.com/kohsuke/winsw) so please refer to [their documentation](https://github.com/kohsuke/winsw/blob/master/doc/xmlConfigFile.md#service-account).
