### ISSUE TITLE
Service cannot be stopped properly

### ISSUE THREAD

**Issue by Runomu** [snicoll-scratches/spring-boot-daemon#2]
i have 3 modules. one of them has just scheduling tasks. another one has jmslisteners and other one has a tcp server socket. module with schedulers can be stopped properly on demand. But other 2  can not be stopped properly. i think connections for tcp socket and activemq block stopping these modules. ?

**Comment by snicoll** [comment]
For some reason, I was't receiving any notification on this repo. Sorry for the late reply,I don't think this has anything to do with the Windows service wrapper. When you say module, you mean app/service, right?

**Comment by Runomu** [comment]
i mean 3 jar modules. i couldnt solve restart and stop problem as windows service using spring-boot-daemon. so i extended JarLaucher like in following link. and made windows service using apache commons daemons prunsrv.exe. now i can stop and restart windows services properly.

http://stackoverflow.com/questions/24124062/spring-boot-jar-as-windows-service

**Comment by snicoll** [comment]
Okay. What are you asking exactly? If I can't reproduce the problem, I won't be able to help you I am afraid. Can you share a sample that exhibits the problem?

**Comment by bdupreez** [comment]
Hi 
I am having the same issue.. I simply install... start.. and try stop.. 
from the log it seems it starts another process when stopping (bold below)..?

The Only way to get it to stop.. is to kill the service process and the extra java process running.

my-boot-0.0.1-SNAPSHOT-windows (develop)
$ ./my-boot.exe install

my-boot-0.0.1-SNAPSHOT-windows (develop)
$ net start my-boot
The Nautilus service is starting.
The Nautilus service was started successfully.

my-boot-0.0.1-SNAPSHOT-windows (develop)
$ net stop my-boot
The Nautilus service is stopping........
The Nautilus service could not be stopped.

my-boot-0.0.1-SNAPSHOT-windows (develop)
$ net stop my-boot
The service is starting or stopping.  Please try again later.

From the log:
2016-06-28 12:22:42 - Starting java  -Dspring.application.admin.enabled=true -Dcom.sun.management.jmxremote.port=50201 -Dcom.sun.management.jmxremote.authenticate=false "-Dcom.sun.management.jmxremote.ssl=false " -cp my-boot-0.0.1-SNAPSHOT/lib/\* net.nicoll.boot.daemon.StartSpringBootService my.boot.Application 
2016-06-28 12:22:42 - Started 9164
2016-06-28 12:22:53 - Stopping my-boot
**2016-06-28 12:22:53 - Started 10332**
2016-06-28 12:22:53 - WaitForProcessToExit 9164+10332

**Comment by snicoll** [comment]
Same question, sorry. Can you share a sample that reproduces the problem?

**Comment by bdupreez** [comment]
I'll have to strip out some of our business code.. On second thought.. I'll try create a dummy project and see if it has the same behavior .. Will see if I have time this evening

**Comment by bdupreez** [comment]
Hi, I just uploaded a simple version that does behave the same:

[https://github.com/bdupreez/boot-service-example](url)

The only changes I made to your example was to add to the path.. as it placed the lib and logs in an artifact path:
**service.xml :** 

```
<logpath>%BASE%\@project.artifactId@-@project.version@\logs</logpath>


<startargument>@project.artifactId@-@project.version@/lib/*</startargument>

```

In creating this comment,I realized what the issue was... 

I did not update the: 
`<stopargument>`

after correcting that, the service stop was successful

**Comment by snicoll** [comment]
I guess the original reporter had a similar issue then. @Runomu feel free to reopen if you have a sample to share.
