### ISSUE TITLE
Dependencies in jar

### ISSUE THREAD

**Issue by mejmo** [snicoll-scratches/spring-boot-daemon#20]
Do you think, it is possible to pack dependencies in jar instead of lib in this configuration. I mean.. I do this all the time but I wonder, if there is any reason that you have it in `lib` instead of jar. Thanks.

**Comment by snicoll** [comment]
The executable script is using a classpath like invocation. You can easily tune that to run a fat jar if you want to.

**Comment by mejmo** [comment]
No this is not possible. Thing is, you cannot call a SpringBootService class from outside of the jar, because of spring boot packaging. All dependencies are in `BOOT-INF/lib` and compiled classes in `BOOT-INF/classes`, so SpringBootService is in thick jar as another jar file.

So it looks like this:

```
thick-jar.jar
  BOOT-INF/classes (compiled output)
  BOOT-INF/lib (dependecies with spring-boot-daemon-integration.jar)
  org/springframework/loader/... <- loader
```
It is simply not possible for **winsw** to call something from BOOT-INF/lib. In your example it is easy, because `java -cp lib/* <classname>` just works, but `java -cp thick-jar.jar; <classname>` will never work. 

I tried to use ```<layout>MODULE</layout>``` but this is quite deprecated and as well it does not pack the loader I think, it is not executable. However, the classes are then in the root of JAR file (as in older Spring Boot versions <1.3.8) which can then help to expose Spring-boot-integration classes (again not aj jar, but as compiled output).

**Comment by snicoll** [comment]
Why do you ask if you know the answer then :)

**Comment by snicoll** [comment]
I haven't tried but [this may be interesting](https://dzone.com/articles/spring-boot-as-a-windows-service-in-5-minutes)

**Comment by mejmo** [comment]
I just wanted to save time for others who struggle to solve this :)

That example uses your project, and yeah.. it packs the dependencies into `/lib`. He also states, he could not get procrun running, I think mostly because of this problem :) Older examples just worked because of  older Spring boot packaging. I will have to live with that `lib/` directory then :(

**Comment by snicoll** [comment]
I am confused. Aren't they using `java -jar` as launch argument? That's using the fat jar isn't it?

**Comment by mejmo** [comment]
Yes this works... but... They do not use `<startargument>` and ```<stopargument>```, they just use ```<arguments>``` which uses then `TerminateProcess` API to kill the application. This will cut the possibility to gracefully shutdown the application. 

```
2018-02-13 19:16:48 - Stopping im-app
2018-02-13 19:16:48 - ProcessKill 13412
2018-02-13 19:16:48 - Found child process: 23128 Name: conhost.exe
2018-02-13 19:16:48 - Stopping process 23128
2018-02-13 19:16:48 - Send SIGINT 23128
2018-02-13 19:16:48 - SIGINT to 23128 failed - Killing as fallback
2018-02-13 19:16:48 - Stopping process 13412
2018-02-13 19:16:48 - Send SIGINT 13412
2018-02-13 19:16:48 - SIGINT to 13412 failed - Killing as fallback
2018-02-13 19:16:48 - Finished im-app
```
I have large application which cannot be stopped forcibly so this is not an option. I will investigate further, how to catch that signal...

**Comment by mejmo** [comment]
Ok I find a solution for now... I will just have two files. `thick.jar` and `service-helper.jar`. I start the first one and then with stop I use `<stopexecutable>` which connects to spring boot actuator and calls `/shutdown`. It is similar approach, but not with JMX... just use plain HTTP.
