### ISSUE TITLE
rename project GroupId

### ISSUE THREAD

**Issue by mtbadi39** [snicoll-scratches/spring-boot-daemon#5]
Hi;
can you please rename the **project groupId** and **package** (com.example) ?
ex : use com.github 
Thanks!

**Comment by snicoll** [comment]
Why?

**Comment by mtbadi39** [comment]
I think that this is an interesting project and **com.example** was inappropriate !

**Comment by snicoll** [comment]
I don't think it is inappropriate (it _is_ a sample after all). But I don't have an objection to use a real grouId either so I just did that.
