### ISSUE TITLE
Similar artifact in Maven Central?

### ISSUE THREAD

**Issue by Pytry** [snicoll-scratches/spring-boot-daemon#8]
I noticed that Maven Central and repo.spring,io have a version of this project deployed with a different groupId and version, but the source code is from this project. 

```
<dependency>
    <groupId>net.kemitix</groupId>
    <artifactId>spring-boot-daemon-integration</artifactId>
    <version>1.1.0</version>
</dependency>
```

Could you clarify the intended use of this projects artifacts and code, as far as its use ion other projects?
Is "spring-boot-daemon-integration" also intended to be published to Maven Central or SpringIO repositories using the "net.nicoll" groupId and version?
Did you or do you intend for the "spring-boot-daemon-integration" module to be used as a dependency in other projects, or was this just sample code meant to be "copy-pasted" into other projects?
Do you know anything about what/who is publishing the "net.kemitix" artifact (I could not find a publicly forked repository)?

**Comment by snicoll** [comment]
I have no idea what `net.kemitix`is. repo.spring.io doesn't have a version for that artifact (at least I didn't find one). It looks like someone decided to fork this repository and release it with its own groupId. This project is a sample for demonstration purpose. There's not a lot of code so you can easily apply that in your own project.

Obviously the person who forked it thinks differently.
